version: '3'

services: 
  app:
    build:
      context: node
    container_name: app-node-mysql-deps
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks: 
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
      - db
    networks: 
      - node-mysql-deps-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db-node-mysql-deps
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-mysql-deps-network

networks: 
  node-mysql-deps-network:
    driver: bridge