version: '3'

services: 
  app:
    build:
      context: node
    container_name: app-node-mysql
    networks: 
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    networks: 
      - node-mysql-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db-node-mysql
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-mysql-network

networks: 
  node-mysql-network:
    driver: bridge