version: '3'

services: 
  app:
    build:
      context: node
    container_name: app-node
    networks: 
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"

networks: 
  node-network:
    driver: bridge